server {
  listen 80;

  # simple health
  location = /healthz {
    return 200 "ok\n";
  }

  # frontend page (served by nginx)
  location = / {
    default_type text/html;
    return 200 "<h2>Hit Counter</h2><p>Open <a href='/api/'>/api/</a> to increment the counter.</p>";
  }

  # reverse proxy to python
  location /api/ {
    proxy_pass http://app:5000/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
